### ISSUE TITLE
Tool Gets only "www." responses by default

### ISSUE THREAD

**Issue by ounissi-zakaria** [xnl-h4ck3r/waymore#44] opened 2024-04-13 14:53 UTC
Hello @xnl-h4ck3r hope you are having a nice day,
I noticed that the tool gets urls from all subs but it only downloads responses from `www.` subdomain. I checked the code and saw this 
https://github.com/xnl-h4ck3r/waymore/blob/d9e2ded597d120ac9b8b5285d55f1f440e13456c/waymore/waymore.py#L2829-L2834

`action="strore_true"` meaning that `--no-subs` is the running on a default of `true`. shouldn't it be `store_false` or am i misunderstanding it ? If you think it's a bug I can  make a quick PR to fix it.

**Comment by xnl-h4ck3r** [comment] 2024-04-15 15:24
Hi @ounissi-zakaria. It does get all subs, unless you pass `-n`/`--no-subs`. If you do pass that for `example.com` then it will get everything for `example.com` and `www.example.com` but no other sub domains. The `action='store_true'` means that if the argument is passed, it will be True. I'll close this as it is working as intended and there is no need for a PR. Thanks

**Closed by xnl-h4ck3r** 2024-04-15 15:24 UTC

**Comment by ounissi-zakaria** [comment] 2024-04-15 15:30
Thanks @xnl-h4ck3r, sorry for the stupid questions 😅 I thought store_true means default is true. 
I still feel like something is missing. I'll do more testing and if there's something i'll tell you.
Regards

**Comment by xnl-h4ck3r** [comment] 2024-04-15 19:13
> Thanks @xnl-h4ck3r, sorry for the stupid questions 😅 I thought store_true means default is true. I still feel like something is missing. I'll do more testing and if there's something i'll tell you. Regards

Not a stupid question at all! Thanks for taking the time to raise an issue. If you do spot the problem, just let me know. Using `-v` may help with the testing. Many thanks

**Comment by xnl-h4ck3r** [comment] 2024-04-16 10:58
Hi @ounissi-zakaria. You are absolutely right! There is a bug with respones! Thanks so much for testing and spotting this
I hve fixed this already and will release today. Can you raise a new Issue with this specific problem so that I can reference it when I put it live, and also, do you have a twitter handle so that I can credit you for spotting this when I put it live?
Many thanks!!

**Comment by ounissi-zakaria** [comment] 2024-04-16 11:11
Thanks for fixing it @xnl-h4ck3r really appreciate it. I created new issue #45 and you can find on twitter @zakaria_ounissi.
Have a nice day

**Comment by xnl-h4ck3r** [comment] 2024-04-16 11:24
> Thanks for fixing it @xnl-h4ck3r really appreciate it. I created new issue #45 and you can find on twitter [@zakaria_ounissi.](https://twitter.com/zakaria_ounissi) Have a nice day

Thanks! I'll update the issue and let you know when the fix is available. Much appreciated. Have a great day too
