### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by TerickJojo** [xnl-h4ck3r/waymore#24] opened 2023-06-16 06:50 UTC
command: `python3 waymore.py -i foo.com -mode U -l 0 -t 6 -oU foo.txt`
OS: Ubuntu
python: 3.11.2
config: default
![image](https://github.com/xnl-h4ck3r/waymore/assets/24235319/dfb3ae78-4aee-496e-806e-401d952f9278)

**Comment by xnl-h4ck3r** [comment] 2023-06-16 09:08
Hi @TerickJojo 
Thanks for using waymore and taking the time to raise an issue for this.
Is it possible to let me know what domain you actually used when you got this error so that I can reproduce it and look into it?
Regards
Xnl

**Comment by xnl-h4ck3r** [comment] 2023-06-16 11:17
Hi
Unfotuntely I can't reproduce the same problem. 
Can you double check that you have the latest version of waymore?
Also, do you have a file called `tesla.com` or `stackoverflow.com` in the directory you are running it? Maybe it is identifying a file and trying to process the contents of that?
Thanks
Xnl

**Comment by xnl-h4ck3r** [comment] 2023-06-16 12:13
To clarify, don't set `-oU` to the name of the domain because it will run first time, but the next time you run it, it will see the output file and assume that is the input and try to read URLs from that. Was that what was happening in this case?

**Comment by xnl-h4ck3r** [comment] 2023-06-16 13:25
Can you use the `-v` argument to see if there are any clues why that might be happening on that machine?

**Comment by xnl-h4ck3r** [comment] 2023-06-16 13:29
Thank you, much appreciated. Have a great weekend too!

**Comment by xnl-h4ck3r** [comment] 2023-06-19 09:38
Great! Thanks for taking the time to figure out what the issue was. I'll get that sorted soon

**Comment by xnl-h4ck3r** [comment] 2023-06-19 15:47
This has been fixed in v1.21 now. Thanks again

**Closed by xnl-h4ck3r** 2023-06-19 15:47 UTC
